# Create numpy array using python "array like" data types

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.23.0


In [3]:
my_list=[-17,0,4,5,9]

my_array_from_list=np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

Elementry Multiplication

In [4]:
list_1=[1,2,3]
a=list_1*5
a

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
my_array_from_list*10

array([-170,    0,   40,   50,   90])

In [6]:
my_tuple=(14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

# Difference between python and numpy data structure

In [7]:
my_tuple*5

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [9]:
np.array(my_tuple)*5

array([ 70.  +0.j, -17.7 +0.j,  25. +35.j])

#  Intrinsic NumPy array creation using numpy's method

In [10]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [12]:
len(np.arange(10,23))

13

In [12]:
my_range_array=np.arange(10,23)
my_range_array.size

13

In [13]:
np.arange(10,23,5)

array([10, 15, 20])

In [15]:
np.arange(25, step=5)

array([ 0,  5, 10, 15, 20])

# numpy.matrix.transpose

In [13]:
a = np.array([[1, 2], [3, 4]]).T
a

array([[1, 3],
       [2, 4]])

In [15]:
a.transpose()

array([[1, 2],
       [3, 4]])

# linspace(), zeros(), ones(), and NumPy data types

In [16]:
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [21]:
my_linspace=np.linspace(0,360,10, retstep=True)
my_linspace
# a=np.arange(0,360,10)
# a

(array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.]), 40.0)

In [18]:
# print(a)
my_linspace

(array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.]), 40.0)

In [19]:
my_linspace[1]

40.0

# Zeros Function

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Ones Function

In [29]:
 np.ones(5, dtype='int32')

array([1, 1, 1, 1, 1])

In [26]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
np.zeros(5, dtype='int32')

array([0, 0, 0, 0, 0])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Slicing Array

In [23]:
my_vector=np.array([-17,-4,0,2,21,37,105])
(my_vector)

array([-17,  -4,   0,   2,  21,  37, 105])

In [24]:
my_vector[0]

-17

In [25]:
my_vector[0]=-102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [30]:
my_vector[-3]

21

In [27]:
my_vector[105]

IndexError: index 105 is out of bounds for axis 0 with size 7

In [28]:
305%7

4

In [29]:
my_vector[305%7]

21

In [40]:
my_vector.size

7

In [41]:
my_vector[305%my_vector.size]

21

# Two Dimensional Array

In [31]:
my_array=np.arange(1,36).reshape(7,5)
my_array.shape=(7,5)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
my_array[2]

array([11, 12, 13, 14, 15])

In [50]:
my_array[-2]

array([26, 27, 28, 29, 30])

In [52]:
my_array[5][2]

28

In [ ]:
row=5
column=2
my_array[row,column]

In [ ]:
my_array[5][2]

# Three Dimensional Array

In [33]:
my_3D_array=np.arange(70).reshape(2,7,5)
# my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [34]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [35]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [36]:
my_3D_array[1,3,2]

52

In [60]:
my_3D_array[1,3,2]=1111
my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

In [ ]:
import numpy as np

# Boolean Mask Array

In [61]:
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [38]:
zero_mode_7_mask=0==(my_vector%7)
zero_mode_7_mask

array([False, False,  True, False,  True, False,  True])

In [39]:
sub_array=my_vector[zero_mode_7_mask]
sub_array

array([  0,  21, 105])

In [64]:
sub_array[sub_array>0]

array([ 21, 105])

In [ ]:
 sub_array

# NumPy Logical Operators

In [66]:
mod_test=0==(my_vector%7)
possitive_test=my_vector > 0
print(mod_test)
print(possitive_test)
combined_mask=np.logical_and(mod_test, possitive_test)
combined_mask

[False False  True False  True False  True]
[False False False  True  True  True  True]


array([False, False, False, False,  True, False,  True])

In [67]:
my_vector[combined_mask]

array([ 21, 105])

# Broadcasting : It defines that how numpy perform operations with an array of different sizes

In [40]:
my_3D_array=np.arange(70).reshape(2,7,5)
# my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [41]:
#Shape
my_3D_array.shape


(2, 7, 5)

In [42]:
#Number of dimensions
my_3D_array.ndim

3

In [43]:
#Size
my_3D_array.size

70

In [44]:
#datatype for each elements
my_3D_array.dtype

dtype('int32')

In [45]:
5*my_3D_array-2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [47]:
left_mat=np.arange(6).reshape((2,3))
print(left_mat)
right_mat=np.arange(6).reshape((3,2))
print(right_mat)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [49]:
np.inner(left_mat.T, right_mat)

array([[ 3,  9, 15],
       [ 4, 14, 24],
       [ 5, 19, 33]])

In [50]:
np.dot(left_mat, right_mat)


array([[10, 13],
       [28, 40]])

# Operation along axis: Broadcasting along particular axis

In [51]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [52]:
my_3D_array.sum()

2415

In [53]:
my_2D_array=np.arange(15).reshape(3,5)
my_2D_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
my_2D_array.sum(axis=0)

array([15, 18, 21, 24, 27])

In [85]:
my_2D_array.sum(axis=1)

array([10, 35, 60])

In [ ]:
# my_3D_array.sum(axis=2)

# Broadcasting Rules

In [14]:
my_2D_array=np.ones(35, dtype="int").reshape(7,5)*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [55]:
my_random_2D_array=np.random.randn(7,5)
my_random_2D_array

array([[-0.67796621,  1.19193962, -1.39446208, -0.93404265, -0.87332319],
       [-1.25336028, -1.90280081,  1.92096761,  2.37277578, -1.50106658],
       [ 1.55001327,  0.48670019,  0.71500599,  1.49080549, -0.41557348],
       [-1.21310919, -1.95973824, -0.99877659,  0.83124847, -0.57437089],
       [-0.10599609, -0.35371664,  0.1359765 , -0.17226889, -0.32809499],
       [ 0.90925302, -1.09607602,  1.44830841,  1.28157493,  0.11364241],
       [-0.25141919, -1.30113076, -1.62138211, -1.20823141,  0.06432854]])

In [15]:
np.set_printoptions(precision=4)
my_2D_array*my_random_2D_array

array([[ 4.3963, -1.5092, -1.384 , -3.9843,  0.7876],
       [-3.3077,  1.8438,  4.3363,  0.1231, -1.4385],
       [ 2.2725,  1.1513, -0.2759,  4.9067, -6.7355],
       [-2.2536,  3.8632, -2.1941,  3.2517, -4.4601],
       [ 0.9663, -4.0292, -3.1291,  0.4797,  0.3834],
       [ 1.9065, -4.3336,  7.1572,  3.1064,  4.8429],
       [-4.8364,  3.4182, -1.9309,  1.0034, -1.8537]])

In [89]:
my_vector=np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [90]:
my_3D_array*my_vector

array([[[   0,    7,   28,   63,  112],
        [  -5,   42,   98,  168,  252],
        [ -10,   77,  168,  273,  392],
        [ -15,  112,  238,  378,  532],
        [ -20,  147,  308,  483,  672],
        [ -25,  182,  378,  588,  812],
        [ -30,  217,  448,  693,  952]],

       [[ -35,  252,  518,  798, 1092],
        [ -40,  287,  588,  903, 1232],
        [ -45,  322,  658, 1008, 1372],
        [ -50,  357,  728, 1113, 1512],
        [ -55,  392,  798, 1218, 1652],
        [ -60,  427,  868, 1323, 1792],
        [ -65,  462,  938, 1428, 1932]]])