In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.21.1


In [1]:
list_1=[1,2,3]
a=list_1*5
print(a)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
a= np.array([[1,2],[3,4]])
# put  .T  after array to transpose
a

array([[1, 2],
       [3, 4]])

In [11]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [12]:
np.linspace(5,15,9)
#  put retstep=True to find step size

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [16]:
# my_linspace=np.linspace(0,360,10,retstep=True)
# my_linspace

a=np.arange(0,360,10)
a


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(5,dtype='int32')

array([1, 1, 1, 1, 1])

In [20]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [24]:
my_vector=np.array([-17,-4,0,2,21,37,105])
(my_vector)

array([-17,  -4,   0,   2,  21,  37, 105])

In [25]:
my_vector[0]

-17

In [26]:
my_vector[0]=-102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [27]:
305%7

4

In [28]:
my_vector[305%4]

-4

In [29]:
my_vector[305%my_vector.size]

21

In [31]:
my_array=np.arange(1,36).reshape(7,5) 
#  my_array.shape=(7,5)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [33]:
my_array[2,3]

#  for getting(fetching)  any element,    2 row 3 column

14

In [37]:
row=5
column=2
my_array=([row,column])

In [38]:
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [42]:
zero_mode_7_mask=0==(my_vector%7)
zero_mode_7_mask


sub_array=my_vector[zero_mode_7_mask]
sub_array

array([  0,  21, 105])

In [7]:
left_mat=np.arange(6).reshape((2,3))
print(left_mat)
right_mat=np.arange(6).reshape((3,2))
print(right_mat)
                    

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [9]:
np.inner(left_mat.T,right_mat)

array([[ 3,  9, 15],
       [ 4, 14, 24],
       [ 5, 19, 33]])

In [10]:
np.dot(left_mat,right_mat)

array([[10, 13],
       [28, 40]])